### ISSUE TITLE
Why the Attack Started is so slow?

### ISSUE THREAD

**Issue by GuckTubeYT** [zile42O/Layer7-CF_bypass#1]
how to i reduce it?

**Comment by GuckTubeYT** [comment]
when i attack 100 threads = so sloooowww

**Comment by zile42O** [comment]
Because you really don't have powerfull vds for that, is need very strong configuration of vds. Try with 5-10, 100is too much

**Comment by GuckTubeYT** [comment]
Oh

**Comment by GuckTubeYT** [comment]
i use vps, not vds

**Comment by GuckTubeYT** [comment]
but, i need to make fast started attacking

**Comment by Cosmysd** [comment]
> but, i need to make fast started attacking

Because is really a big shit script, leaked 100 times, public on all forums, also all methods are patched (cf,ddg, etc)
So stop using this shit, If you really want something powerful, then get started and learn to code your own script.
Or pay someone to do it

**Comment by zile42O** [comment]
I really now don't have time for updating this, so if someone want and know to optimize and fast up the script then open PR. This is public not private like said Cosmysd..

**Comment by Cosmysd** [comment]
> I really now don't have time for updating this, so if someone want and know to optimize and fast up the script then open PR. This is public not private like said Cosmysd..

I can fix this, but I couldn't publish it for free, why? because if I published it for free many children would use it and say that it is fixed by them, and the script would end up being sold

**Comment by zile42O** [comment]
I not have currently time for updating this i can do it soon.
